name: Build Executables
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Auto-locate and Move Script
        shell: bash
        run: |
          find . -maxdepth 3 -name "*.py" ! -name "build.yml" -exec cp {} ./app_to_build.py \;
          ls -R

      - name: Install dependencies
        run: |
          pip install numpy matplotlib scipy PyQt5 ezc3d kineticstoolkit pyinstaller

      - name: Build with PyInstaller
        # Added logic to name the file based on the OS
        shell: bash
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            APP_NAME="GaitApp_Windows"
          else
            APP_NAME="GaitApp_macOS"
          fi
          pyinstaller --noconsole --onefile --collect-all kineticstoolkit --name "$APP_NAME" app_to_build.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          # This will now create folders named 'GaitApp_Windows' or 'GaitApp_macOS'
          name: GaitApp_${{ matrix.os == 'windows-latest' && 'Windows' || 'macOS' }}
          path: dist/
