name: Build Executables
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        # We install the libraries directly here so we don't need the requirements.txt file
        run: |
          pip install kineticstoolkit PyQt5 matplotlib numpy
          pip install pyinstaller

      - name: Build with PyInstaller
        # We use quotes just in case there are hidden spaces in the folder name
        run: |
          pyinstaller --noconsole --onefile --collect-all kineticstoolkit "PHED-4137/ HipOA .py"
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          # This name is just the label for the ZIP file you download
          name: HipOA-Build-${{ matrix.os }}
          path: dist/
